#!/usr/bin/env node
// Shared helpers for keeping allowlist.json (the single source of truth for
// parent-admin emails) and firestore.rules (which must carry its own copy,
// since Firestore rules can't fetch external config at eval time) in sync.
//
// Used by:
//   sync-allowlist.js       — regenerates the rules block from allowlist.json
//   check-allowlist-sync.js — CI check, fails if they've drifted apart

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ALLOWLIST_PATH = path.join(ROOT, 'allowlist.json');
const RULES_PATH = path.join(ROOT, 'firestore.rules');

const START_MARKER = '// ALLOWLIST:START';
const END_MARKER = '// ALLOWLIST:END';

function loadParents() {
  const raw = fs.readFileSync(ALLOWLIST_PATH, 'utf8');
  const data = JSON.parse(raw);
  if (!Array.isArray(data.parents) || data.parents.length === 0) {
    throw new Error(`allowlist.json has no "parents" array — refusing to sync`);
  }
  return data.parents.map((e) => String(e).trim().toLowerCase());
}

function loadRulesText() {
  return fs.readFileSync(RULES_PATH, 'utf8');
}

// Builds the exact block of rules text that should sit between the markers.
function buildGeneratedBlock(parents, indent) {
  const lines = [];
  lines.push(`${indent}${START_MARKER} — generated by scripts/sync-allowlist.js, do not hand-edit`);
  lines.push(`${indent}&& request.auth.token.email.lower() in [`);
  parents.forEach((email, i) => {
    const comma = i < parents.length - 1 ? ',' : '';
    lines.push(`${indent}     '${email}'${comma}`);
  });
  lines.push(`${indent}   ];`);
  lines.push(`${indent}${END_MARKER}`);
  return lines.join('\n');
}

// Extracts the parent emails currently embedded in firestore.rules, by
// pulling out every 'quoted@email' string between the markers.
function extractRulesParents(rulesText) {
  const startIdx = rulesText.indexOf(START_MARKER);
  const endIdx = rulesText.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `firestore.rules is missing ${START_MARKER} / ${END_MARKER} markers — can't locate the allowlist block`
    );
  }
  const block = rulesText.slice(startIdx, endIdx);
  const matches = [...block.matchAll(/'([^']+@[^']+)'/g)];
  return matches.map((m) => m[1].toLowerCase());
}

// Replaces the marker-delimited block in firestore.rules with a freshly
// generated one built from allowlist.json. Returns the new file text.
function regenerateRulesText(rulesText, parents) {
  const startIdx = rulesText.indexOf(START_MARKER);
  const endIdx = rulesText.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `firestore.rules is missing ${START_MARKER} / ${END_MARKER} markers — can't locate the allowlist block`
    );
  }
  // Detect the indentation used on the START marker line so regeneration
  // matches the surrounding style.
  const lineStart = rulesText.lastIndexOf('\n', startIdx) + 1;
  const indent = rulesText.slice(lineStart, startIdx);

  const endOfEndMarkerLine = rulesText.indexOf('\n', endIdx);
  const before = rulesText.slice(0, lineStart);
  const after = endOfEndMarkerLine === -1 ? '' : rulesText.slice(endOfEndMarkerLine);

  return before + buildGeneratedBlock(parents, indent) + after;
}

function arraysEqualAsSets(a, b) {
  const sa = new Set(a);
  const sb = new Set(b);
  if (sa.size !== sb.size) return false;
  for (const x of sa) if (!sb.has(x)) return false;
  return true;
}

module.exports = {
  loadParents,
  loadRulesText,
  extractRulesParents,
  regenerateRulesText,
  arraysEqualAsSets,
  RULES_PATH,
  ALLOWLIST_PATH,
};
